---
- name: Create main Datadog agant yaml configuration file (beta)
  template:
    src: kafka.yml.j2
    dest: /etc/datadog-agent/conf.d/kafka.d/conf.yaml
    owner: '{{ datadog_user }}'
    group: '{{ datadog_group }}'
  notify: restart datadog-agent

