---

- name: Copy repo file into place
  template: src=datadog.repo.j2 dest=/etc/yum.repos.d/datadog.repo owner=root group=root mode=0644

- name: Install pinned datadog-agent package
  yum:
    name: datadog-agent-{{ datadog_agent_version }}
    state: present
  when: datadog_agent_version != ""

- name: Install latest datadog-agent package
  yum:
    name: datadog-agent
    state: latest
  when: datadog_agent_version == ""
