---

- name: Copy repo file into place
  template: src=datadog.list.j2 dest=/etc/apt/sources.list.d/datadog.list owner=root group=root mode=0644

- name: Ensure Datadog repository is up-to-date
  apt_repository:
    repo: "{{ datadog_apt_repo }}"
    state: "{% if datadog_agent6 %}absent{% else %}present{% endif %}"
    update_cache: yes

- name: Install latest datadog-agent package
  yum:
    name: datadog-agent
    state: latest
  when: datadog_agent_version == "1:6.16.0-1"
